name: LiveStream-workflow
on:
  push:
    branches:
      - master  
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_TOKEN  }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    strategy:
      matrix:
        os: [linux]
        version: [node1, node2, node3,node3]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Tar file
        run: tar -cvf code.tar .
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: code.tar
  Deploy-Dev:
    strategy:
      matrix:
        os: [linux]
        version: [node1, node2, node3,node3]
    runs-on: ${{ matrix.os }}
    needs: [Clone-down]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: stop all containers, remove all images
        run: chmod +x ci/stop-containers.sh && ci/stop-containers.sh
      - name: Deploy docker containers
        run: docker-compose up -d
  Test: 
      strategy:
        matrix:
          os: [linux]
          version: [node1, node2, node3,node3]
      runs-on: ${{ matrix.os }}
      needs: [Deploy-Dev]
      steps:
        - name: test availability of frontend
          run: chmod +x ci/test-app.sh && ci/test-app.sh


